# taken from https://docs.ecommons.chalmers.se/apps/files/?dir=/Infragroup/Mimer&openfile=460779
[global]
fsid = dab1e177-d6d2-4fd1-b1a9-ed7cf93d87d9
mon_host = [v2:10.43.20.1:3300/0,v1:10.43.20.1:6789/0] [v2:10.43.20.2:3300/0,v1:10.43.20.2:6789/0] [v2:10.43.20.3:3300/0,v1:10.43.20.3:6789/0]

# inspired from https://eugene.debeste.co.za/posts/2018-08-23-ceph-erasure-openstack/
# because per default the <pool>.data is not used for data
[client.dev-cirrus.glance]
rbd default data pool = dev-cirrus.glance.data

[client.dev-cirrus.cinder-backup]
rbd default data pool = dev-cirrus.cinder-backup.data

[client.dev-cirrus.vms-ec]
rbd default data pool = dev-cirrus.vms-ec.data
